In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('melb_data.csv')

In [3]:
data.head()

,Unnamed: 0,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,CouncilArea_Moreland,CouncilArea_Nillumbik,CouncilArea_Port Phillip,CouncilArea_Stonnington,CouncilArea_Unavailable,CouncilArea_Whitehorse,CouncilArea_Whittlesea,CouncilArea_Wyndham,CouncilArea_Yarra,CouncilArea_Yarra Ranges
0,0,Abbotsford,85 Turner St,-0.981463,h,0.632448,S,Biggin,3/12/2016,-1.301485,...,False,False,False,False,False,False,False,False,True,False
1,1,Abbotsford,25 Bloomburg St,-0.981463,h,-0.063640,S,Biggin,4/02/2016,-1.301485,...,False,False,False,False,False,False,False,False,True,False
2,2,Abbotsford,5 Charles St,0.064876,h,0.608984,SP,Biggin,4/03/2017,-1.301485,...,False,False,False,False,False,False,False,False,True,False
3,3,Abbotsford,40 Federation La,0.064876,h,-0.353025,PI,Biggin,4/03/2017,-1.301485,...,False,False,False,False,False,False,False,False,True,False
4,4,Abbotsford,55a Park St,1.111216,h,0.820157,VB,Nelson,4/06/2016,-1.301485,...,False,False,False,False,False,False,False,False,True,False

In [4]:
data.describe()

,Unnamed: 0,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount,Suburb-Encoded
count,13580.000000,1.358000e+04,1.358000e+04,1.358000e+04,1.358000e+04,1.358000e+04,1.358000e+04,1.351800e+04,1.358000e+04,13580.000000,13580.000000,1.358000e+04,1.358000e+04,1.358000e+04,1.358000e+04
mean,6789.500000,-3.097506e-16,1.402249e-16,-8.371638e-17,8.455354e-16,1.590611e-16,-1.067384e-16,6.728027e-17,2.092909e-18,-0.022799,0.056451,2.372260e-14,-9.082390e-14,-8.371638e-18,8.162347e-17
std,3920.352663,1.000037e+00,1.000037e+00,1.000037e+00,1.000037e+00,1.000037e+00,1.000037e+00,1.000037e+00,1.000037e+00,0.725017,0.780453,1.000037e+00,1.000037e+00,1.000037e+00,1.000037e+00
min,0.000000,-2.027803e+00,-1.549670e+00,-1.727488e+00,-1.161329e+00,-3.017674e+00,-2.218118e+00,-1.672636e+00,-1.399356e-01,-0.280914,-20.623919,-4.710596e+00,-5.421969e+00,-1.645666e+00,-1.719825e+00
25%,3394.750000,-9.814634e-01,-6.658730e-01,-6.880412e-01,-6.760722e-01,-9.470352e-01,-7.723755e-01,-6.337802e-01,-9.558050e-02,-0.055395,-0.125678,-6.008280e-01,-6.314608e-01,-7.021750e-01,-9.446698e-01
50%,6789.500000,6.487613e-02,-2.701197e-01,-1.597980e-01,-2.349296e-01,8.828423e-02,-7.723755e-01,4.050752e-01,-2.967434e-02,-0.048001,0.142623,8.639920e-02,4.699962e-02,-2.054205e-01,-1.448380e-02
75%,10184.250000,6.487613e-02,3.978117e-01,4.877259e-01,4.708986e-01,8.828423e-02,6.733667e-01,4.050752e-01,2.320094e-02,-0.040718,0.276774,6.662225e-01,6.071385e-01,6.569909e-01,8.714076e-01
max,13579.000000,7.389253e+00,1.239555e+01,6.468802e+00,9.613579e+00,1.768871e+01,9.347820e+00,8.715918e+00,1.083707e+02,82.005456,1.430471,5.055367e+00,5.111394e+00,3.242170e+00,1.746225e+00

In [5]:
data.shape

(13580, 55)

In [6]:
data.isnull().sum()

Unnamed: 0                        0
Suburb                            0
Address                           0
Rooms                             0
Type                              0
Price                             0
Method                            0
SellerG                           0
Date                              0
Distance                          0
Postcode                          0
Bedroom2                          0
Bathroom                          0
Car                              62
Landsize                          0
BuildingArea                      0
YearBuilt                         0
Lattitude                         0
Longtitude                        0
Regionname                        0
Propertycount                     0
Suburb-Encoded                    0
CouncilArea_Banyule               0
CouncilArea_Bayside               0
CouncilArea_Boroondara            0
CouncilArea_Brimbank              0
CouncilArea_Cardinia              0
CouncilArea_Casey                 0
CouncilArea_Darebin               0
CouncilArea_Frankston             0
CouncilArea_Glen Eira             0
CouncilArea_Greater Dandenong     0
CouncilArea_Hobsons Bay           0
CouncilArea_Hume                  0
CouncilArea_Kingston              0
CouncilArea_Knox                  0
CouncilArea_Macedon Ranges        0
CouncilArea_Manningham            0
CouncilArea_Maribyrnong           0
CouncilArea_Maroondah             0
CouncilArea_Melbourne             0
CouncilArea_Melton                0
CouncilArea_Monash                0
CouncilArea_Moonee Valley         0
CouncilArea_Moorabool             0
CouncilArea_Moreland              0
CouncilArea_Nillumbik             0
CouncilArea_Port Phillip          0
CouncilArea_Stonnington           0
CouncilArea_Unavailable           0
CouncilArea_Whitehorse            0
CouncilArea_Whittlesea            0
CouncilArea_Wyndham               0
CouncilArea_Yarra                 0
CouncilArea_Yarra Ranges          0
dtype: int64

In [7]:
mean_car = data['Car'].mean()

In [8]:
data['Car'] = data['Car'].fillna(value = mean_car)

In [9]:
data.isnull().sum()

Unnamed: 0                       0
Suburb                           0
Address                          0
Rooms                            0
Type                             0
Price                            0
Method                           0
SellerG                          0
Date                             0
Distance                         0
Postcode                         0
Bedroom2                         0
Bathroom                         0
Car                              0
Landsize                         0
BuildingArea                     0
YearBuilt                        0
Lattitude                        0
Longtitude                       0
Regionname                       0
Propertycount                    0
Suburb-Encoded                   0
CouncilArea_Banyule              0
CouncilArea_Bayside              0
CouncilArea_Boroondara           0
CouncilArea_Brimbank             0
CouncilArea_Cardinia             0
CouncilArea_Casey                0
CouncilArea_Darebin              0
CouncilArea_Frankston            0
CouncilArea_Glen Eira            0
CouncilArea_Greater Dandenong    0
CouncilArea_Hobsons Bay          0
CouncilArea_Hume                 0
CouncilArea_Kingston             0
CouncilArea_Knox                 0
CouncilArea_Macedon Ranges       0
CouncilArea_Manningham           0
CouncilArea_Maribyrnong          0
CouncilArea_Maroondah            0
CouncilArea_Melbourne            0
CouncilArea_Melton               0
CouncilArea_Monash               0
CouncilArea_Moonee Valley        0
CouncilArea_Moorabool            0
CouncilArea_Moreland             0
CouncilArea_Nillumbik            0
CouncilArea_Port Phillip         0
CouncilArea_Stonnington          0
CouncilArea_Unavailable          0
CouncilArea_Whitehorse           0
CouncilArea_Whittlesea           0
CouncilArea_Wyndham              0
CouncilArea_Yarra                0
CouncilArea_Yarra Ranges         0
dtype: int64

In [10]:
data.dtypes

Unnamed: 0                         int64
Suburb                            object
Address                           object
Rooms                            float64
Type                              object
Price                            float64
Method                            object
SellerG                           object
Date                              object
Distance                         float64
Postcode                         float64
Bedroom2                         float64
Bathroom                         float64
Car                              float64
Landsize                         float64
BuildingArea                     float64
YearBuilt                        float64
Lattitude                        float64
Longtitude                       float64
Regionname                        object
Propertycount                    float64
Suburb-Encoded                   float64
CouncilArea_Banyule                 bool
CouncilArea_Bayside                 bool
CouncilArea_Boroondara              bool
CouncilArea_Brimbank                bool
CouncilArea_Cardinia                bool
CouncilArea_Casey                   bool
CouncilArea_Darebin                 bool
CouncilArea_Frankston               bool
CouncilArea_Glen Eira               bool
CouncilArea_Greater Dandenong       bool
CouncilArea_Hobsons Bay             bool
CouncilArea_Hume                    bool
CouncilArea_Kingston                bool
CouncilArea_Knox                    bool
CouncilArea_Macedon Ranges          bool
CouncilArea_Manningham              bool
CouncilArea_Maribyrnong             bool
CouncilArea_Maroondah               bool
CouncilArea_Melbourne               bool
CouncilArea_Melton                  bool
CouncilArea_Monash                  bool
CouncilArea_Moonee Valley           bool
CouncilArea_Moorabool               bool
CouncilArea_Moreland                bool
CouncilArea_Nillumbik               bool
CouncilArea_Port Phillip            bool
CouncilArea_Stonnington             bool
CouncilArea_Unavailable             bool
CouncilArea_Whitehorse              bool
CouncilArea_Whittlesea              bool
CouncilArea_Wyndham                 bool
CouncilArea_Yarra                   bool
CouncilArea_Yarra Ranges            bool
dtype: object

In [11]:
data['Car'] = data['Car'].astype('int')
data['Address'] = data['Address'].astype('string')
data['Rooms'] = data['Rooms'].astype('int')

In [12]:
data.dtypes

Unnamed: 0                                int64
Suburb                                   object
Address                          string[python]
Rooms                                     int64
Type                                     object
Price                                   float64
Method                                   object
SellerG                                  object
Date                                     object
Distance                                float64
Postcode                                float64
Bedroom2                                float64
Bathroom                                float64
Car                                       int64
Landsize                                float64
BuildingArea                            float64
YearBuilt                               float64
Lattitude                               float64
Longtitude                              float64
Regionname                               object
Propertycount                           float64
Suburb-Encoded                          float64
CouncilArea_Banyule                        bool
CouncilArea_Bayside                        bool
CouncilArea_Boroondara                     bool
CouncilArea_Brimbank                       bool
CouncilArea_Cardinia                       bool
CouncilArea_Casey                          bool
CouncilArea_Darebin                        bool
CouncilArea_Frankston                      bool
CouncilArea_Glen Eira                      bool
CouncilArea_Greater Dandenong              bool
CouncilArea_Hobsons Bay                    bool
CouncilArea_Hume                           bool
CouncilArea_Kingston                       bool
CouncilArea_Knox                           bool
CouncilArea_Macedon Ranges                 bool
CouncilArea_Manningham                     bool
CouncilArea_Maribyrnong                    bool
CouncilArea_Maroondah                      bool
CouncilArea_Melbourne                      bool
CouncilArea_Melton                         bool
CouncilArea_Monash                         bool
CouncilArea_Moonee Valley                  bool
CouncilArea_Moorabool                      bool
CouncilArea_Moreland                       bool
CouncilArea_Nillumbik                      bool
CouncilArea_Port Phillip                   bool
CouncilArea_Stonnington                    bool
CouncilArea_Unavailable                    bool
CouncilArea_Whitehorse                     bool
CouncilArea_Whittlesea                     bool
CouncilArea_Wyndham                        bool
CouncilArea_Yarra                          bool
CouncilArea_Yarra Ranges                   bool
dtype: object

In [13]:
data['Method'].value_counts()

Method
S     9022
SP    1703
PI    1564
VB    1199
SA      92
Name: count, dtype: int64

In [22]:
# data['Method'] = data['Method'].map({'S':0, 'SP':1, 'PI':2, 'VB':3, 'SA':4})

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data['Regionname'] = le.fit_transform(data['Regionname'])
data['Regionname'].value_counts()

Regionname
5    4695
2    3890
6    2948
0    1471
4     450
1      53
3      41
7      32
Name: count, dtype: int64

In [23]:
#label Encoding
data['Method'] = le.fit_transform(data['Method'])
data['Method'].value_counts()

Method
1    9022
3    1703
0    1564
4    1199
2      92
Name: count, dtype: int64

In [35]:
data_dummy = pd.get_dummies(data, columns=['Method'], drop_first=True)

In [39]:
data.head()

,Unnamed: 0,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,CouncilArea_Nillumbik,CouncilArea_Port Phillip,CouncilArea_Stonnington,CouncilArea_Unavailable,CouncilArea_Whitehorse,CouncilArea_Whittlesea,CouncilArea_Wyndham,CouncilArea_Yarra,CouncilArea_Yarra Ranges,method_label
0,0,Abbotsford,85 Turner St,0,h,0.632448,1,Biggin,3/12/2016,-1.301485,...,False,False,False,False,False,False,False,True,False,1
1,1,Abbotsford,25 Bloomburg St,0,h,-0.063640,1,Biggin,4/02/2016,-1.301485,...,False,False,False,False,False,False,False,True,False,1
2,2,Abbotsford,5 Charles St,0,h,0.608984,3,Biggin,4/03/2017,-1.301485,...,False,False,False,False,False,False,False,True,False,3
3,3,Abbotsford,40 Federation La,0,h,-0.353025,0,Biggin,4/03/2017,-1.301485,...,False,False,False,False,False,False,False,True,False,0
4,4,Abbotsford,55a Park St,1,h,0.820157,4,Nelson,4/06/2016,-1.301485,...,False,False,False,False,False,False,False,True,False,4

In [37]:
data['Method'].value_counts()

Method
1    9022
3    1703
0    1564
4    1199
2      92
Name: count, dtype: int64